### ISSUE TITLE
add support react 18

### ISSUE THREAD

**Issue by meded90** [samdenty/console-feed#114]

**Comment by achirita** [comment]
I'm using console-feed with React 18,2 and it seems to be working fine, you just have to use `--legacy-peer-deps` when installing the dependency.

It might just be a case of adding 18.x to the react peer dependencies.
```
"peerDependencies": {
    "react": "^15.x || ^16.x || ^17.x || ^18.x"
  },
```

**Comment by meded90** [comment]
It would be convenient if added to the component
https://stackoverflow.com/a/30454133
