### ISSUE TITLE
Use with srcdoc

### ISSUE THREAD

**Issue by BoyWithSilverWings** [samdenty/console-feed#14]
Issue:

`console-feed` does not seem to work with `src-doc` attribute.

Reproduction: https://codesandbox.io/s/5wx6qlox1n

When the same content is provided as `src` attribute (you can test by changing `srcdoc` to `src=iframe.html`), it shows logs.

**Comment by gonzarascon** [comment]
I have a similar issue here, have you found a solution?

**Comment by samdenty** [comment]
You should use the `Hook` function on `iframe.contentWindow.console`

**Comment by gonzarascon** [comment]
Yes, that works if you have an `iframe.html` separately and give that file as a `src` attribute to the `<iframe />`  element on js.  But it still doesn't work with the `srcDoc` attribute.

**Comment by BoyWithSilverWings** [comment]
@gonzarascon I ended up ditching `console-feed` and settled on a custom solution. You can find that [here](https://blog.agney.dev/override-console-on-iframe/)

**Comment by samdenty** [comment]
@gonzarascon @BoyWithSilverWings Ah I see. I've debugged it, and it seems that the iframe with a `srcdoc` is loaded two-times. In the `componentDidMount` after you've called the Hook function, the iframe is reloaded meaning the console isn't hooked anymore.

You can prevent this by using `setTimeout` or wrapping it inside a `iframe.addEventListener('load', () => {})`

https://codesandbox.io/s/625r54ql8n

**Comment by gonzarascon** [comment]
You have an example of `Hook` inside an iframe? If the `srcDoc` of the iframe is updated, the console un-hooks again.

**Comment by samdenty** [comment]
Iframe:

```js
import { Hook, Encode } from 'console-feed'

Hook(window.console, log => {
	window.postMessage(log, '*')
})
```

Parent:

```js
import { Decode } from 'console-feed'

window.addEventListener('message', (log) => {
	Decode(log)
})
```

**Comment by pratik-pdw** [comment]
@samdenty postMessage doesn't work well with objects containing functions. It throws a DataCloneError. Is there a better way to Hook the iFrame Console ? Also, it doesn't work well in React Hooks.
