### ISSUE TITLE
is it possible to get the built artifact?

### ISSUE THREAD

**Issue by noelgolding** [samdenty/console-feed#16]
I am new to npm and don't know the full ecosystem required to build these types of projects.  Ideally I would like to download the javascript that has been built for the browser, then I hope to simply reference that js file in my html and be able to use the component on my site.  Please let me know if this is possible.

**Comment by noelgolding** [comment]
I would like my html to look something like:

`
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Console test</title>
    <script src="/scripts/console-feed.min.js"></script>
  </head>
  <body>
    <console-feed></console-feed>
  </body>
</html>
`

**Comment by samdenty** [comment]
Console feed requires react to be used. The next version that I intend to release will be framework independent
