### ISSUE TITLE
Text and icon are misaligned when changing font size

### ISSUE THREAD

**Issue by Janglee123** [samdenty/console-feed#17]
When you change font size of the console, icons are not lined with text or in other words icons are not centered vertically. Changing Icon height with font size doesn't solve issue. I tried to multiply icon height with some number (like 1.5*fontsize) to align  it vertically but it is not working for all sizes.

Here is [demo](https://codesandbox.io/s/3vjlwprw76)

**Comment by AnkurIngale** [comment]
Can you look into this?
<img width="851" alt="Screenshot 2019-03-15 at 3 15 30 AM" src="https://user-images.githubusercontent.com/33569473/54393669-c001dc00-46d0-11e9-8dae-d5a00b48f380.png">
I tried this and they are pretty much close to each other. But the problem is, different icons and text are set differently making it very difficult for all of them to come together.

**Comment by AnkurIngale** [comment]
https://codesandbox.io/s/rl7pk9w2ym
Also on testing the same here, the problem is with the react console-feed itself. Therefore, we need some sort of mapping function which maps padding to fontsize. That will do the job.

**Comment by Janglee123** [comment]
@AnkurIngale I think mapping values are not a proper solution. If you want to help just clone the repo and find what is going wrong. I suspect this [line](https://github.com/samdenty/console-feed/blob/aa698128afdbedf518c51e5070ed5914d35691a6/src/Component/elements.tsx#L61). Fix it by changing to something else.

**Comment by matthewoates** [comment]
They're also blurry on displays where the physical pixel ratio is > 1, which is pretty much every device now.

**Comment by matthewoates** [comment]
rich objects have similar positioning issues. eg: `console.log('deep object', { foo: { bar: { baz: 1234, qux: 'ok' }}});`
<img width="456" alt="Screen Shot 2022-07-19 at 9 30 38 PM" src="https://user-images.githubusercontent.com/3092315/179897283-e8c19c98-9fe1-45b6-bc7d-d66efaaa422d.png">
