### ISSUE TITLE
Recursion error logging React children (with hooks)

### ISSUE THREAD

**Issue by koenbok** [samdenty/console-feed#19]
Thanks for the great library!

I seem to have ran into an eccentric recursion issue. 

- Open https://codesandbox.io/s/qq1z439rjq
- Open web inspector and record timeline
- Enter some new items in high succession

You can quickly notice the page slowing down. When you inspect the log you get a result like this:

![image](https://user-images.githubusercontent.com/206779/56167005-4f9ff080-5fd7-11e9-912e-155138623460.png)

cc @compuives CodeSandbox has this too!

**Comment by samdenty** [comment]
Internally, [replicator](https://www.npmjs.com/package/replicator) is currently used to serialize objects (so they can be transferred between DOM's), those stack frames are from within replicator.

The alternative way to handle recursion to use a two-way, which serializes objects as you expand them (the way chrome devtools does).

I haven't done this, as I've previously managed to get chrome devtools working embedded on a website using a mocked version of the devtools websocket API - giving you the real devtools, but I haven't put much time into that.

**Comment by samdenty** [comment]
note: you can avoid the serializing / deserializing step, if the iframe is same-origin

**Comment by koenbok** [comment]
In our own app (Framer) we get this error too, but there console-feed just lives in the same page (so no iframe like CodeSandbox). Any hints how we could avoid this error in that setup?

**Comment by samdenty** [comment]
https://github.com/samdenty/console-feed/blob/8cca0ef2b994edbe286e082567f412134f761bde/src/Hook/index.ts#L47

Encode function should be removed

**Comment by koenbok** [comment]
Would you be interested in a PR to make this an option? Or should we fork the library for our use case?

**Comment by samdenty** [comment]
@koenbok PR would be ideal, `Hook(cb, encode = true` so it's not a major update

**Comment by nvh** [comment]
@samdenty I just created a PR for this ^

**Comment by samdenty** [comment]
Available in [2.8.7](https://www.npmjs.com/package/console-feed#disabling-serialization)

**Comment by koenbok** [comment]
Thanks!
