### ISSUE TITLE
Support for emotion v10

### ISSUE THREAD

**Issue by aron** [samdenty/console-feed#27]
Hey, I just wanted to start a discussion about support for [emotion v10](https://emotion.sh/docs/migrating-to-emotion-10) and I’ve been unable to get two packages one depending on v9 and the other v10 running side-by-side.

Fortunately the upgrade was straight forward. I’ve a fork of the [project working with v10](https://github.com/framer/console-feed/tree/emotion-v10) let me know if you’d like me to open a PR against this repo. Though I don’t know how you’d like to handle backwards compatibility.

Cheers,
Aron

**Comment by samdenty** [comment]
Pull request would be great. Backwards compat shouldn't be an issue as it isn't directly exposed
