### ISSUE TITLE
Object in "real" console is null in console-feed

### ISSUE THREAD

**Issue by sannek** [samdenty/console-feed#55]
console-feed version: 2.8

I'm investigating a [CodeSandbox bug](https://github.com/codesandbox/codesandbox-client/issues/4980) someone reported  where a `Proxy{}` object (Vue) gets output as `null` in the CodeSandbox console, and this might be a bug in console-feed?

The linked issue has more details, and I'm happy to help dive into it more if I can (or pass it on to one of our frontend developers - who are perhaps more useful than me as a backend dev)

Thanks!

**Comment by samdenty** [comment]
Seems like a bug in the JSON serialisation - https://github.com/samdenty/console-feed/blob/2fca873a168f0e70369e0f273d5c4b174e102b32/src/Transform/index.ts#L15. Maybe a faulty transform / issue of the replicator.ts file.

**Comment by sannek** [comment]
Thanks for your quick reply! That sounds like it's not going to be an easy thing to figure out?

**Comment by samdenty** [comment]
fixed in 3.1.1

**Comment by sannek** [comment]
Perfect - thank you for figuring that out! We'll update to the latest version.
