### ISSUE TITLE
How to use hooks with TypeScript?

### ISSUE THREAD

**Issue by 5a34e1bf4ed6581ce7c13bc05c7d0855** [samdenty/console-feed#57]
There are multiple types called "Message", one in console.d.ts and one in component.d.ts. Console component takes props of type Message[] (the readme states is takes Log[] I think) and this is the type from component.d.ts, but the Hook takes the type from console.d.ts. I have something like this:
```typescript
import { useState, useEffect } from "react";
import { Console, Hook, Unhook } from "console-feed";
import { Message as MessageComponent } from "console-feed/lib/definitions/Component";
import { Message as MessageConsole } from "console-feed/lib/definitions/Console";

const LogsContainer = () => {
  const [logs, setLogs] = useState<MessageConsole[]>([]);

  // run once!
  useEffect(() => {
    Hook(
      window.console,
      (log) => setLogs((currLogs) => [...currLogs, log]),
      false
    );
    return () => {Unhook(window.console as any)};
  }, []);

  return <Console logs={logs as MessageComponent[]} variant="dark" />;
};

export { LogsContainer };
```
I wonder if something should be done to make the experience more seamless in TS? Error is thrown when copy pasting from the example.

**Comment by samdenty** [comment]
library could do with a rewrite, didn't initially publish types so yeah I wouldn't use them

**Comment by 5a34e1bf4ed6581ce7c13bc05c7d0855** [comment]
Thanks! If I have issues that require modifying source I'll try to make a reasonable pull. For now the hacky approach seems alright. Thanks for releasing the library, helping a lot with a personal project.

**Comment by softmarshmallow** [comment]
Still not resolved. re-open please

**Comment by HoverBaum** [comment]
Thanks so much for the workaround @5a34e1bf4ed6581ce7c13bc05c7d0855 . First line should import React though:

```
import React, { useState, useEffect } from 'react'
```
