### ISSUE TITLE
Issue with log grouping

### ISSUE THREAD

**Issue by bodinsamuel** [samdenty/console-feed#59]
There is an issue related to recent changes: #52 by @RealPeha 

With empty log
```js
  console.log();
  console.log("a");
  console.log("b");
  console.log("c");

// Output
// (4)
```

## Screenshots
<img width="395" alt="Screenshot 2020-10-12 at 14 46 36" src="https://user-images.githubusercontent.com/1637651/95748086-c5068300-0c99-11eb-85cf-fce22b815af0.png">

## Repro
https://codesandbox.io/s/console-feed-forked-ugjmf?file=/src/demo/index.js

Sidenote: This behavior should probably be an option instead of mandatory as in chrome

**Comment by RealPeha** [comment]
Interesting
Thanks, i will fix it!

**Comment by bodinsamuel** [comment]
thanks @RealPeha much appreciated 🙏🏻
