### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by lbogdan** [samdenty/console-feed#61]
Sometimes `message` can be `undefined` in https://github.com/samdenty/console-feed/blob/637125cb868f5eba59df0751d0bf128ae4577241/src/Component/message-parsers/Error.tsx#L5

Steps to reproduce:

- open https://codesandbox.io/s/missing-error-firebase-5rlbf
- wait for it to load
- console should show a badge with 2 errors
- click on it
- you should get a CodeSadbox page

![image](https://user-images.githubusercontent.com/2083930/95861710-82f94200-0d6a-11eb-99d6-cf983137d78d.png)

@samdenty Let me know if you need more info on this.

**Comment by samdenty** [comment]
fixed in 3.1.9
